from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from fractions import Fraction
from math import gcd


# ============================================================
# MIKROTIK INTERFACE LISTS
# ============================================================

# Interfaces whose NEW Internet-bound connections participate
# in PCC load balancing.
#
# Example:
#
#   OFFICE
#   STUDENT
#   RESIDENT
#
# can all be members of the RouterOS "PCC" interface list.
#
PCC_INTERFACE_LIST = "PCC"

# All WAN interfaces.
#
# Example:
#
#   eth1-WAN-ISP1
#   eth2-WAN-ISP2
#
WAN_INTERFACE_LIST = "WAN"


# Prefix used to identify rules generated by this script.
AUTO_PCC_PREFIX = "AUTO-PCC"


# ============================================================
# DATA MODELS
# ============================================================

@dataclass(frozen=True)
class ISP:
    name: str
    bandwidth_mbps: Decimal

    # MikroTik WAN interface.
    interface: str

    # Connection mark used by Mangle.
    connection_mark: str

    # RouterOS v7 routing table.
    routing_mark: str


@dataclass(frozen=True)
class ISPPlan:
    isp: ISP

    # Actual bandwidth percentage.
    exact_percentage: Decimal

    # Number of PCC buckets assigned to this ISP.
    bucket_count: int

    # PCC bucket numbers.
    buckets: tuple[int, ...]

    # Actual PCC percentage.
    pcc_percentage: Decimal


@dataclass(frozen=True)
class PCCPlan:
    isps: tuple[ISP, ...]

    # Exact simplified bandwidth ratio.
    exact_ratio: tuple[int, ...]

    # Actual PCC bucket distribution.
    bucket_ratio: tuple[int, ...]

    # Total number of PCC buckets.
    total_buckets: int

    # True when bucket ratio exactly represents
    # the bandwidth ratio.
    exact: bool

    plans: tuple[ISPPlan, ...]


# ============================================================
# NUMBER / RATIO HELPERS
# ============================================================

def to_decimal(
    value: int | float | str | Decimal,
) -> Decimal:
    return Decimal(str(value))


def decimal_to_fraction(
    value: Decimal,
) -> Fraction:
    return Fraction(value)


def simplify_ratio(
    values: list[int],
) -> tuple[int, ...]:
    """
    Simplify an integer ratio using GCD.

    Examples:

        [100, 30]      -> (10, 3)
        [65, 25]       -> (13, 5)
        [100, 45]      -> (20, 9)
        [100, 30, 40]  -> (10, 3, 4)
    """

    if not values:
        raise ValueError(
            "Ratio cannot be empty."
        )

    if any(value <= 0 for value in values):
        raise ValueError(
            "Ratio values must be greater than zero."
        )

    divisor = values[0]

    for value in values[1:]:
        divisor = gcd(
            divisor,
            value,
        )

    return tuple(
        value // divisor
        for value in values
    )


def exact_integer_weights(
    values: list[Decimal],
) -> list[int]:
    """
    Convert Decimal bandwidth values into exact integer
    weights without losing precision.

    Example:

        [100, 30] -> [100, 30]
        simplified -> 10:3
    """

    if not values:
        raise ValueError(
            "At least one value is required."
        )

    if any(value <= 0 for value in values):
        raise ValueError(
            "Values must be greater than zero."
        )

    fractions = [
        decimal_to_fraction(value)
        for value in values
    ]

    common_denominator = 1

    for fraction in fractions:
        common_denominator = (
            common_denominator
            * fraction.denominator
            // gcd(
                common_denominator,
                fraction.denominator,
            )
        )

    return [
        fraction.numerator
        * (
            common_denominator
            // fraction.denominator
        )
        for fraction in fractions
    ]


# ============================================================
# BUCKET ALLOCATION
# ============================================================

def largest_remainder_allocation(
    weights: list[Decimal],
    total_buckets: int,
) -> tuple[int, ...]:
    """
    Allocate PCC buckets proportionally using the
    largest-remainder method.

    Used only when the exact simplified ratio is
    larger than max_buckets.
    """

    if total_buckets <= 0:
        raise ValueError(
            "total_buckets must be greater than zero."
        )

    if not weights:
        raise ValueError(
            "At least one weight is required."
        )

    if any(weight <= 0 for weight in weights):
        raise ValueError(
            "Weights must be greater than zero."
        )

    if total_buckets < len(weights):
        raise ValueError(
            "total_buckets must be at least "
            "the number of ISPs."
        )

    total_weight = sum(weights)

    raw_values = [
        weight
        / total_weight
        * Decimal(total_buckets)
        for weight in weights
    ]

    base_values = [
        int(value)
        for value in raw_values
    ]

    remaining = (
        total_buckets
        - sum(base_values)
    )

    remainders = [
        (
            raw_values[index]
            - Decimal(base_values[index]),
            index,
        )
        for index in range(len(raw_values))
    ]

    remainders.sort(
        key=lambda item: item[0],
        reverse=True,
    )

    for _, index in remainders[:remaining]:
        base_values[index] += 1

    return tuple(base_values)


def choose_bucket_ratio(
    bandwidths: list[Decimal],
    max_buckets: int,
) -> tuple[tuple[int, ...], bool]:
    """
    Select PCC bucket distribution.

    Priority:

        1. Exact simplified bandwidth ratio.
        2. Largest-remainder approximation.

    Example:

        100 : 30
          ↓
        10 : 3
          ↓
        13 buckets
    """

    if not bandwidths:
        raise ValueError(
            "At least one ISP is required."
        )

    if any(value <= 0 for value in bandwidths):
        raise ValueError(
            "ISP bandwidth must be greater than zero."
        )

    if max_buckets < len(bandwidths):
        raise ValueError(
            "max_buckets must be at least "
            "the number of ISPs."
        )

    integer_weights = exact_integer_weights(
        bandwidths
    )

    exact_ratio = simplify_ratio(
        integer_weights
    )

    exact_total = sum(exact_ratio)

    if exact_total <= max_buckets:
        return (
            exact_ratio,
            True,
        )

    approximate_ratio = largest_remainder_allocation(
        bandwidths,
        max_buckets,
    )

    return (
        approximate_ratio,
        False,
    )


# ============================================================
# CREATE PCC PLAN
# ============================================================

def create_pcc_plan(
    isps: list[ISP],
    max_buckets: int = 50,
) -> PCCPlan:

    if not isps:
        raise ValueError(
            "At least one ISP is required."
        )

    if max_buckets < len(isps):
        raise ValueError(
            "max_buckets must be at least "
            "the number of ISPs."
        )

    bandwidths = [
        isp.bandwidth_mbps
        for isp in isps
    ]

    integer_weights = exact_integer_weights(
        bandwidths
    )

    exact_ratio = simplify_ratio(
        integer_weights
    )

    bucket_ratio, exact = choose_bucket_ratio(
        bandwidths,
        max_buckets,
    )

    total_buckets = sum(
        bucket_ratio
    )

    total_bandwidth = sum(
        bandwidths
    )

    plans: list[ISPPlan] = []

    bucket_start = 0

    for index, isp in enumerate(isps):

        bucket_count = bucket_ratio[index]

        buckets = tuple(
            range(
                bucket_start,
                bucket_start + bucket_count,
            )
        )

        bucket_start += bucket_count

        exact_percentage = (
            isp.bandwidth_mbps
            / total_bandwidth
            * Decimal("100")
        )

        pcc_percentage = (
            Decimal(bucket_count)
            / Decimal(total_buckets)
            * Decimal("100")
        )

        plans.append(
            ISPPlan(
                isp=isp,
                exact_percentage=exact_percentage,
                bucket_count=bucket_count,
                buckets=buckets,
                pcc_percentage=pcc_percentage,
            )
        )

    return PCCPlan(
        isps=tuple(isps),
        exact_ratio=exact_ratio,
        bucket_ratio=bucket_ratio,
        total_buckets=total_buckets,
        exact=exact,
        plans=tuple(plans),
    )


# ============================================================
# ROUTEROS HELPERS
# ============================================================

def pcc_classifier(
    total_buckets: int,
    bucket: int,
) -> str:
    return (
        "both-addresses-and-ports:"
        f"{total_buckets}/{bucket}"
    )


def auto_comment(
    section: str,
    isp_name: str,
    bucket: int | None = None,
) -> str:

    comment = (
        f"{AUTO_PCC_PREFIX} "
        f"{section} "
        f"{isp_name}"
    )

    if bucket is not None:
        comment += f" BUCKET-{bucket}"

    return comment


# ============================================================
# CLEANUP
# ============================================================

def generate_cleanup() -> str:

    return """# ============================================================
# AUTO-PCC CLEANUP
# ============================================================
# Removes ONLY rules generated by this generator.
# Manual Mangle rules are NOT removed.

/ip firewall mangle
remove [find comment~"^AUTO-PCC "]
"""


# ============================================================
# PCC MODEL DOCUMENTATION
# ============================================================

def generate_pcc_model_documentation(
    plan: PCCPlan,
) -> str:

    lines = [
        "# ============================================================",
        "# PCC MODEL",
        "# ============================================================",
        "#",
        "# PCC interface list:",
        "#",
        f"#   {PCC_INTERFACE_LIST}",
        "#",
        "# WAN interface list:",
        "#",
        f"#   {WAN_INTERFACE_LIST}",
        "#",
        "# Bandwidth:",
        "#",
    ]

    for isp in plan.isps:
        lines.append(
            f"#   {isp.name} = "
            f"{isp.bandwidth_mbps} Mbps"
        )

    lines.extend(
        [
            "#",
            "# Exact bandwidth ratio:",
            "#",
            "#   "
            + " : ".join(
                str(value)
                for value in plan.exact_ratio
            ),
            "#",
            "# PCC bucket ratio:",
            "#",
            "#   "
            + " : ".join(
                str(value)
                for value in plan.bucket_ratio
            ),
            "#",
            f"# Total PCC buckets: {plan.total_buckets}",
            "#",
            "# Distribution:",
            "#",
        ]
    )

    for isp_plan in plan.plans:

        lines.append(
            "#   "
            f"{isp_plan.isp.name} = "
            f"{isp_plan.bucket_count} buckets "
            f"= {isp_plan.pcc_percentage:.2f}%"
        )

    lines.extend(
        [
            "#",
            "# Exact:",
            "#",
            "#   "
            + (
                "YES"
                if plan.exact
                else "NO - APPROXIMATED"
            ),
            "#",
            "# ============================================================",
        ]
    )

    return "\n".join(lines) + "\n"


# ============================================================
# PCC BUCKET -> ISP MAPPING
# ============================================================

def generate_bucket_mapping(
    plan: PCCPlan,
) -> str:

    lines = [
        "# ============================================================",
        "# PCC BUCKET -> ISP MAPPING",
        "# ============================================================",
        "#",
        "# PCC classifier:",
        "#",
        f"#   both-addresses-and-ports:"
        f"{plan.total_buckets}/<bucket>",
        "#",
        "# Bucket   ISP     Connection Mark   Routing Table",
        "# ------   ------  ----------------  -------------",
    ]

    for isp_plan in plan.plans:

        isp = isp_plan.isp

        for bucket in isp_plan.buckets:

            lines.append(
                "# "
                f"{bucket:>6}   "
                f"{isp.name:<6}  "
                f"{isp.connection_mark:<16}  "
                f"{isp.routing_mark}"
            )

    lines.extend(
        [
            "#",
            "# ============================================================",
        ]
    )

    return "\n".join(lines) + "\n"


# ============================================================
# INBOUND WAN CONNECTION MARKING
# ============================================================

def generate_inbound_connection_rules(
    plan: PCCPlan,
) -> str:

    lines = [
        "# ============================================================",
        "# AUTO-PCC INBOUND WAN CONNECTION MARKING",
        "# ============================================================",
        "#",
        "# Internet -> Router/LAN connections are marked",
        "# according to the WAN interface on which they arrive.",
        "#",
        "# This preserves connection symmetry for:",
        "#",
        "#   - dst-nat / port forwarding",
        "#   - public services",
        "#   - inbound connections",
        "#   - reply traffic",
        "#",
        "/ip firewall mangle",
    ]

    for isp in plan.isps:

        lines.append(
            "add "
            "chain=prerouting "
            f"in-interface={isp.interface} "
            "connection-state=new "
            "connection-mark=no-mark "
            "action=mark-connection "
            f"new-connection-mark={isp.connection_mark} "
            "passthrough=yes "
            f'comment="{auto_comment("INBOUND", isp.name)}"'
        )

    return "\n".join(lines) + "\n"


# ============================================================
# PCC CONNECTION MARKING
# ============================================================

def generate_pcc_connection_rules(
    plan: PCCPlan,
) -> str:

    lines = [
        "# ============================================================",
        "# AUTO-PCC CONNECTION MARKING",
        "# ============================================================",
        "#",
        f"# PCC interface list = {PCC_INTERFACE_LIST}",
        "#",
        "# Only NEW, unmarked connections entering through",
        "# the PCC interface list are classified.",
        "#",
        "# IMPORTANT:",
        "#",
        "# NET-INTERNAL and NET-VPN bypass rules must be placed",
        "# BEFORE these AUTO-PCC rules.",
        "#",
        f"# PCC buckets: {plan.total_buckets}",
        "#",
        "/ip firewall mangle",
    ]

    for isp_plan in plan.plans:

        isp = isp_plan.isp

        for bucket in isp_plan.buckets:

            classifier = pcc_classifier(
                plan.total_buckets,
                bucket,
            )

            lines.append(
                "add "
                "chain=prerouting "
                f"in-interface-list={PCC_INTERFACE_LIST} "
                "connection-state=new "
                "connection-mark=no-mark "
                "dst-address-type=!local "
                f"per-connection-classifier={classifier} "
                "action=mark-connection "
                f"new-connection-mark={isp.connection_mark} "
                "passthrough=yes "
                f'comment="{auto_comment("CONNECTION", isp.name, bucket)}"'
            )

    return "\n".join(lines) + "\n"


# ============================================================
# CONNECTION MARK -> ROUTING MARK
# ============================================================

def generate_policy_routing_rules(
    plan: PCCPlan,
) -> str:

    lines = [
        "# ============================================================",
        "# AUTO-PCC CONNECTION MARK -> ROUTING MARK",
        "# ============================================================",
        "#",
        "# IMPORTANT:",
        "#",
        "# PCC interface membership is checked ONLY when a NEW",
        "# connection is classified above.",
        "#",
        "# Once the connection has ISPx_CM, routing is based",
        "# on the connection mark for the entire connection.",
        "#",
        "# Therefore this section intentionally does NOT use:",
        "#",
        f"#   in-interface-list={PCC_INTERFACE_LIST}",
        "#",
        "/ip firewall mangle",
    ]

    for isp in plan.isps:

        lines.append(
            "add "
            "chain=prerouting "
            f"connection-mark={isp.connection_mark} "
            "dst-address-type=!local "
            "action=mark-routing "
            f"new-routing-mark={isp.routing_mark} "
            "passthrough=no "
            f'comment="{auto_comment("ROUTE", isp.name)}"'
        )

    return "\n".join(lines) + "\n"


# ============================================================
# INBOUND REPLY ROUTING
# ============================================================

def generate_inbound_reply_rules(
    plan: PCCPlan,
) -> str:

    lines = [
        "# ============================================================",
        "# AUTO-PCC INBOUND REPLY ROUTING",
        "# ============================================================",
        "#",
        f"# WAN interface list = {WAN_INTERFACE_LIST}",
        "#",
        "# Internet -> Router/LAN packets use the routing table",
        "# associated with their existing connection mark.",
        "#",
        "/ip firewall mangle",
    ]

    for isp in plan.isps:

        lines.append(
            "add "
            "chain=prerouting "
            f"in-interface-list={WAN_INTERFACE_LIST} "
            f"connection-mark={isp.connection_mark} "
            "action=mark-routing "
            f"new-routing-mark={isp.routing_mark} "
            "passthrough=no "
            f'comment="{auto_comment("INBOUND-ROUTE", isp.name)}"'
        )

    return "\n".join(lines) + "\n"


# ============================================================
# ROUTER OUTPUT
# ============================================================

def generate_output_rules(
    plan: PCCPlan,
) -> str:
    """
    Router-originated NEW connections are intentionally NOT
    PCC classified.

    Existing marked connections are routed according to their
    connection mark.
    """

    lines = [
        "# ============================================================",
        "# AUTO-PCC ROUTER OUTPUT",
        "# ============================================================",
        "#",
        "# Router-originated NEW connections are NOT PCC",
        "# classified by this generator.",
        "#",
        "# Existing marked connections are routed according",
        "# to their connection mark.",
        "#",
        "/ip firewall mangle",
    ]

    for isp in plan.isps:

        lines.append(
            "add "
            "chain=output "
            f"connection-mark={isp.connection_mark} "
            "dst-address-type=!local "
            "action=mark-routing "
            f"new-routing-mark={isp.routing_mark} "
            "passthrough=no "
            f'comment="{auto_comment("OUTPUT-ROUTE", isp.name)}"'
        )

    return "\n".join(lines) + "\n"


# ============================================================
# COMPLETE MANGLE CONFIG
# ============================================================

def generate_mangle_config(
    plan: PCCPlan,
) -> str:

    routing_tables = ", ".join(
        isp.routing_mark
        for isp in plan.isps
    )

    sections = [
        """# ============================================================
# AUTO-GENERATED MIKROTIK PCC CONFIGURATION
# ============================================================
#
# This configuration manages ONLY AUTO-PCC rules.
#
# ============================================================
# MANAGED BY THIS GENERATOR
# ============================================================
#
#   - WAN inbound connection marking
#   - PCC connection marking
#   - Connection mark -> routing mark
#   - Inbound reply routing
#   - Existing marked router-output routing
#
# ============================================================
# NOT MANAGED BY THIS GENERATOR
# ============================================================
#
#   - NET-INTERNAL bypass
#   - NET-VPN bypass
#   - Firewall
#   - NAT
#   - Routing table creation
#   - WAN routes
#   - Failover routes
#   - WireGuard
#
# ============================================================
""",

        generate_pcc_model_documentation(plan),

        generate_bucket_mapping(plan),

        "# ============================================================\n"
        "# REQUIRED ROUTING TABLES\n"
        "# ============================================================\n"
        "#\n"
        f"#   {routing_tables}\n"
        "#\n"
        "# These routing tables must already exist.\n"
        "#\n",

        "# ============================================================\n"
        "# REQUIRED MANGLE ORDER\n"
        "# ============================================================\n"
        "#\n"
        "# Manual bypass rules MUST exist before AUTO-PCC:\n"
        "#\n"
        "#   1. NET-INTERNAL bypass\n"
        "#   2. NET-VPN bypass\n"
        "#\n"
        "# Then AUTO-PCC:\n"
        "#\n"
        "#   3. WAN inbound connection marking\n"
        "#   4. PCC connection marking\n"
        "#   5. Connection mark -> routing mark\n"
        "#   6. Inbound reply routing\n"
        "#   7. Router output routing\n"
        "#\n"
        "# ============================================================\n",

        generate_cleanup(),

        generate_inbound_connection_rules(plan),

        generate_pcc_connection_rules(plan),

        generate_policy_routing_rules(plan),

        generate_inbound_reply_rules(plan),

        generate_output_rules(plan),
    ]

    return "\n".join(sections)


# ============================================================
# CONSOLE REPORT
# ============================================================

def print_report(
    plan: PCCPlan,
) -> None:

    print()
    print("=" * 70)
    print("PCC PLAN")
    print("=" * 70)

    print(
        "PCC interface list:",
        PCC_INTERFACE_LIST,
    )

    print(
        "WAN interface list:",
        WAN_INTERFACE_LIST,
    )

    print()

    print(
        "Bandwidth:",
        " + ".join(
            f"{isp.name}={isp.bandwidth_mbps} Mbps"
            for isp in plan.isps
        ),
    )

    print(
        "Exact ratio:",
        ":".join(
            str(value)
            for value in plan.exact_ratio
        ),
    )

    print(
        "PCC bucket ratio:",
        ":".join(
            str(value)
            for value in plan.bucket_ratio
        ),
    )

    print(
        "Total buckets:",
        plan.total_buckets,
    )

    print(
        "Exact:",
        "YES"
        if plan.exact
        else "NO - APPROXIMATED",
    )

    print()
    print("-" * 70)
    print("ISP DISTRIBUTION")
    print("-" * 70)

    for isp_plan in plan.plans:

        isp = isp_plan.isp

        print()
        print(
            f"[{isp.name}]"
        )

        print(
            f"  Bandwidth       : "
            f"{isp.bandwidth_mbps} Mbps"
        )

        print(
            f"  Exact share     : "
            f"{isp_plan.exact_percentage:.2f}%"
        )

        print(
            f"  PCC share       : "
            f"{isp_plan.pcc_percentage:.2f}%"
        )

        print(
            f"  Bucket count    : "
            f"{isp_plan.bucket_count}"
        )

        print(
            f"  Buckets         : "
            f"{isp_plan.buckets}"
        )

        print(
            f"  Connection mark : "
            f"{isp.connection_mark}"
        )

        print(
            f"  Routing mark    : "
            f"{isp.routing_mark}"
        )

    print()
    print("-" * 70)
    print("PCC BUCKET MAPPING")
    print("-" * 70)

    print(
        f"{'Bucket':>8}  "
        f"{'ISP':<8}  "
        f"{'Connection Mark':<18}  "
        f"Routing Table"
    )

    print("-" * 70)

    for isp_plan in plan.plans:

        isp = isp_plan.isp

        for bucket in isp_plan.buckets:

            print(
                f"{bucket:>8}  "
                f"{isp.name:<8}  "
                f"{isp.connection_mark:<18}  "
                f"{isp.routing_mark}"
            )

    print()
    print("=" * 70)


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    # --------------------------------------------------------
    # ISP DEFINITIONS
    # --------------------------------------------------------

    isps = [
        ISP(
            name="ISP1",
            bandwidth_mbps=Decimal("100"),
            interface="eth1-WAN-ISP1",
            connection_mark="ISP1_CM",
            routing_mark="to_ISP1",
        ),
        ISP(
            name="ISP2",
            bandwidth_mbps=Decimal("30"),
            interface="eth2-WAN-ISP2",
            connection_mark="ISP2_CM",
            routing_mark="to_ISP2",
        ),
    ]

    # --------------------------------------------------------
    # CREATE PCC PLAN
    # --------------------------------------------------------

    plan = create_pcc_plan(
        isps=isps,
        max_buckets=50,
    )

    # --------------------------------------------------------
    # PRINT REPORT
    # --------------------------------------------------------

    print_report(plan)

    # --------------------------------------------------------
    # PRINT ROUTEROS CONFIGURATION
    # --------------------------------------------------------

    print(
        generate_mangle_config(plan)
    )